name: ğŸ“ Generate GTFS JSON

on:
  schedule:
    - cron: "0 3 * * *" # tous les jours Ã  3h UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v4.2.2

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22

      - name: ğŸ’¾ Install dependencies
        run: npm ci

      - name: â–¶ï¸ Run generator
        run: npm run generate:*

      - name: ğŸ›« Commit and push datas if modified
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "ğŸ¤– Maj quotidienne GTFS"
          git push
