name: ğŸ“ Generate GTFS JSON

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v5.0.0

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: ğŸ’¾ Install dependencies
        run: npm ci

      - name: â–¶ï¸ Run generator
        run: npm run generate:*

      - name: ğŸ›« Commit and push datas if modified
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data/

          git diff --cached --quiet || git commit -m "ğŸ¤– Maj quotidienne GTFS + SIRI"
          git push
